"""decisions

Revision ID: panel_0001
Revises:
Create Date: 2026-09-27 18:53:32.944310
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "panel_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "panel_decision",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("assessments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("synthesis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "recommendation",
            sa.Enum(
                "proceed", "revise", "pass", native_enum=False, create_constraint=True, length=64
            ),
            nullable=True,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "proceed", "revise", "pass", native_enum=False, create_constraint=True, length=64
            ),
            nullable=True,
        ),
        sa.Column("outcome_note", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("panel_decision")
    # ### end Alembic commands ###
